default_language_version:
  python: python3.12
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
      - id: detect-private-key
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: "2.7.1"
    hooks:
      - id: editorconfig-checker
        alias: ec
        args:
          - -disable-indent-size
  - repo: https://github.com/asottile/pyupgrade
    rev: "v3.6.0"
    hooks:
      - id: pyupgrade
        args:
          - --py310-plus
  - repo: https://github.com/pycqa/autoflake
    rev: "v2.1.1"
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
          - --ignore-init-module-imports
  - repo: https://github.com/pycqa/isort
    rev: "5.12.0"
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: "23.3.0"
    hooks:
      - id: black
  - repo: https://github.com/asottile/blacken-docs
    rev: "1.14.0"
    hooks:
      - id: blacken-docs
        additional_dependencies: ["black==22.8.0"]
  - repo: https://github.com/pycqa/flake8
    rev: "6.0.0"
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear==22.9.11
          - flake8-comprehensions==3.10.0
  - repo: https://github.com/sirosen/check-jsonschema
    rev: "0.23.2"
    hooks:
      - id: check-github-workflows
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.7.1"
    hooks:
      - id: mypy
        args: ["--strict"]
        pass_filenames: false
        additional_dependencies:
          - pytest==7.4.3
          - types-setuptools==69.0.0.0
          - abcattrs==0.4.0
          - typing-extensions==4.9.0
          - hypothesis==6.92.1
          - pydantic==2.5.2
          - pydantic-core==2.14.5
          - types-babel==2.11.0.15
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1"
    hooks:
      - id: prettier
        alias: format-markdown
        types: [markdown]
        args:
          - --parser=markdown
          - --print-width=88
          - --prose-wrap=always
  - repo: https://github.com/mgedmin/check-manifest
    rev: "0.49"
    hooks:
      - id: check-manifest
        args: ["--no-build-isolation"]
        additional_dependencies:
          - wheel==0.42.0

exclude: |
  (?x)(
    /(
      \.eggs
      | \.git
      | \.hg
      | \.mypy_cache
      | \.pytest_cache
      | \.nox
      | \.tox
      | \.venv
      | _build
      | buck-out
      | build
      | dist
    )/
  )
