default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.2.0"
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
      - id: detect-private-key
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: "2.4.0"
    hooks:
      - id: editorconfig-checker
        alias: ec
        args:
          - -disable-indent-size
  - repo: https://github.com/asottile/pyupgrade
    rev: "v2.33.0"
    hooks:
      - id: pyupgrade
        args:
          - --py310-plus
  - repo: https://github.com/myint/autoflake
    rev: "v1.4"
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports
          - --ignore-init-module-imports
  - repo: https://github.com/pycqa/isort
    rev: "5.10.1"
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: "22.3.0"
    hooks:
      - id: black
  - repo: https://github.com/asottile/blacken-docs
    rev: "v1.12.1"
    hooks:
      - id: blacken-docs
        additional_dependencies: ["black==22.3.0"]
  - repo: https://gitlab.com/pycqa/flake8
    rev: "3.9.2"
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-tidy-imports
  - repo: https://github.com/sirosen/check-jsonschema
    rev: "0.16.0"
    hooks:
      - id: check-github-workflows
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.960"
    hooks:
      - id: mypy
        args: ["--strict"]
        additional_dependencies:
          - pytest
          - types-setuptools
          - phantom-types
          - abcattrs
          - typing-extensions
  - repo: https://github.com/mgedmin/check-manifest
    rev: "0.48"
    hooks:
      - id: check-manifest
        args: ["--no-build-isolation"]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.6.2"
    hooks:
      - id: prettier
        alias: format-markdown
        types: [markdown]
        args:
          - --parser=markdown
          - --print-width=88
          - --prose-wrap=always

exclude: |
  (?x)(
    /(
      \.eggs
      | \.git
      | \.hg
      | \.mypy_cache
      | \.pytest_cache
      | \.nox
      | \.tox
      | \.venv
      | _build
      | buck-out
      | build
      | dist
    )/
  )
