default_language_version:
  python: python3.12
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.5.0"
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements
      - id: detect-private-key
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: "2.7.3"
    hooks:
      - id: editorconfig-checker
        alias: ec
        args:
          - -disable-indent-size
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.1.8"
    hooks:
      - id: ruff
  - repo: https://github.com/psf/black
    rev: "23.12.0"
    hooks:
      - id: black
  - repo: https://github.com/asottile/blacken-docs
    rev: "1.16.0"
    hooks:
      - id: blacken-docs
        additional_dependencies: ["black==23.12.0"]
  - repo: https://github.com/sirosen/check-jsonschema
    rev: "0.27.3"
    hooks:
      - id: check-github-workflows
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
      - id: prettier
        alias: format-markdown
        types: [markdown]
        args:
          - --parser=markdown
          - --print-width=88
          - --prose-wrap=always

  # TODO: This does not work with VCS versioning.
  # - repo: https://github.com/mgedmin/check-manifest
  #   rev: "0.49"
  #   hooks:
  #     - id: check-manifest
  #       args: ["--no-build-isolation"]
  #       additional_dependencies:
  #         - setuptools==71.1.0
  #         - setuptools-scm==8.1.0
  #         - wheel==0.43.0

exclude: |
  (?x)(
    /(
      \.eggs
      | \.git
      | \.hg
      | \.mypy_cache
      | \.pytest_cache
      | \.nox
      | \.tox
      | \.venv
      | _build
      | buck-out
      | build
      | dist
    )/
  )
