name: CI
on:
  push:
    branches:
      - main
  pull_request:

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    name: Static analysis
    uses: less-action/reusables/.github/workflows/pre-commit.yaml@v2
    with:
      python-version: "3.10"

  check-build:
    name: Check packaging metadata
    uses: less-action/reusables/.github/workflows/python-test-build.yaml@v2

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11-dev"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: pip cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('setup.cfg') }}
          restore-keys: ${{ runner.os }}-pip
      - run: pip install -e '.[test]'
      - run: coverage run -m pytest
      - run: |
          coverage report
          coverage xml
      # - uses: codecov/codecov-action@v2
      #   with:
      #     file: coverage.xml
      #     fail_ci_if_error: true
      #     name: codecov-py${{ matrix.python-version }}
