name: CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    name: Static analysis
    uses: less-action/reusables/.github/workflows/pre-commit.yaml@main
    with:
      python-version: "3.10"

  check-build:
    name: Check packaging metadata
    uses: less-action/reusables/.github/workflows/python-test-build.yaml@main

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11-dev"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: pip cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('setup.cfg') }}
          restore-keys: ${{ runner.os }}-pip
      - run: pip install -e '.[test]'
      - run: coverage run -m pytest
      - run: |
          coverage report
          coverage xml
      - uses: codecov/codecov-action@v3
        with:
          file: coverage.xml
          fail_ci_if_error: true
          name: codecov-py${{ matrix.python-version }}

  check-generate-currencies:
    name: Check currencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11-dev"
      - name: pip cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('generate-requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip
      - run: pip install -r generate-requirements.txt
      - run: |
          python generate-currencies.py
          diff=$(git --no-pager diff)
          if [[ ! -z "$diff" ]]; then
            echo "💥 Non-empty output from git diff."
            echo
            echo "$diff"
            exit 1
          else
            echo "✅ No diff to current currency module."
          fi
