name: Release

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    uses: less-action/reusables/.github/workflows/python-publish.yaml@main
    with:
      environment_url: https://pypi.org/p/immoney
