name: Release

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    uses: less-action/reusables/.github/workflows/python-publish.yaml@v3
    secrets:
      pypi_api_token: ${{ secrets.PYPI_API_TOKEN }}
